version: '2.0'
services:
  nginx:
    image: test/rest:v1
    container_name: nginx-container
    networks:
      static-network:
        ipv4_address: 172.17.128.2
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.17.0.0/16
          ip_range: 172.17.5.0/24

